[tool.ruff]
line-length = 100
extend-select = ["E", "F", "I"]
ignore = ["E402", "F401", "F841"]
fix = true

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
strict_optional = false